version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: exchangehub
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - exchange-net
    expose:
      - "5432"

  migrator:
    build: ./ExchangeHub.Migrator
    container_name: migrator
    depends_on:
      - postgres
    networks:
      - exchange-net
    restart: "no"

  userservice:
    build: ./ExchangeHub.UserService
    container_name: userservice
    expose:
      - "5001"
    depends_on:
      migrator:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    networks:
      - exchange-net

  financeservice:
    build: ./ExchangeHub.FinanceService
    container_name: financeservice
    expose:
      - "5002"
    depends_on:
      migrator:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    networks:
      - exchange-net

  currencyworker:
    build: ./ExchangeHub.CurrencyWorker
    container_name: currencyworker
    depends_on:
      migrator:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    networks:
      - exchange-net

  gateway:
    build: ./ExchangeHub.ApiGateway
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - userservice
      - financeservice
    networks:
      - exchange-net

networks:
  exchange-net:
    driver: bridge

volumes:
  postgres_data:
