services:
  exchangehub.userservice:
    build: ./ExchangeHub.UserService
    container_name: userservice
    expose:
      - "5001"
    networks:
      - exchange-net
  
  exchangehub.financeservice:
    build: ./ExchangeHub.FinanceService
    container_name: financeservice
    expose:
      - "5002"
    networks:
      - exchange-net
  
  exchangehub.currencyworker:
    build: ./ExchangeHub.CurrencyWorker
    container_name: currencyworker
    networks:
      - exchange-net
    depends_on:
      - userservice
      - financeservice
      - postgres
  
  exchangehub.migrator:
    build: ./ExchangeHub.Migrator
    container_name: migrator
    depends_on:
      - postgres
    networks:
      - exchange-net
    restart: "no"
    command: [ "dotnet", "ExchangeHub.Migrator.dll" ]
  
  gateway:
    build: ./ExchangeHub.ApiGateway
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - userservice
      - financeservice
    networks:
      - exchange-net